title: "Leap"
description: Computer Science. Technology. Impression
url: "https://nsaikiran.github.io"
baseurl: "/blog"

markdown: kramdown
plugins:
  - jekyll-paginate
  - kramdown
  - rouge
  - jekyll-seo-tag
  - jekyll-relative-links
  - jemoji

#GitHub variables start
# Set by GitHub, Can't override
# So, use in local as well
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
   noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  # Parse markdown inside HTML div
  parse_block_html: true
# GitHub variables end


#Collections
collections:
  drafts:
    output: true
    permalink: /:collection/:name
  short_notes:
    output: true
    permalink: /short-notes/:name


google_analytics_id: UA-89879231-1

disqus:
  shortname: "nsaikiran"

social:
  name: Sai Kiran Naragam
  links:
    - https://twitter.com/saikiran638
    - https://www.facebook.com/saikiran638
    - https://www.linkedin.com/in/saikiran638
    - https://github.com/nsaikiran